# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('article_author', models.CharField(max_length=100)),
                ('article_content', models.TextField()),
            ],
        ),
    ]
